os: osx
osx_image: xcode11.2
language: swift
script : xcodebuild clean build test -workspace AirportLocator.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CORE_SIGNING_REQUIRED=NO  